### ISSUE TITLE
thoughts on splitting up the code 

### ISSUE THREAD

**Issue by ashleygwilliams** [yoshuawuyts/npmrc#1]
🔦 question?

i would love to contribute by adding some more [values](https://docs.npmjs.com/files/npmrc) to what this crate parses, however i realized that in order to scale we'll probably want to split this code up into different files. figured i'd file an issue and ask what ya'll thought would be best before i imposed what i thought would be good. also i'm not sure what exactly i think the best answer is 😅 

maybe per enum? or categorize the enums somehow? anyways. interested to hear what ya'll think.

**Comment by sendilkumarn** [comment]
I perfectly agree in splitting the code and making it extensible. 

I would also like this to be a single crate that entirely takes care of `npmrc` 

P.S. I also believe that apart from `wasm-pack` anyone wanna fiddle `npmrc` this should be capable of handling it. That is what I had envisioned when I was suggesting this.

**Comment by ashleygwilliams** [comment]
@sendilkumarn yeah i wasn't saying that this should be separate crates, just trying to see how to split this crate into multiple files to keep it a bit more maintainable

**Comment by sendilkumarn** [comment]
@ashleygwilliams perfect 😄

**Comment by yoshuawuyts** [comment]
@ashleygwilliams that'd be perfect! - yeah, I just put it all into the same file because I wasn't sure how to create (internal) modules; but all in favor of splitting it into separate files!
