### ISSUE TITLE
support per project, global config, and npm builtin config npmrcs

### ISSUE THREAD

**Issue by ashleygwilliams** [yoshuawuyts/npmrc#2]
🙋 feature request

## Current Behavior

currently, this crate hardcodes the presence of an `npmrc` in the user's home directory. (https://github.com/yoshuawuyts/npmrc/blob/master/src/lib.rs#L126) 

## Expected Behavior
to mimic how npm reads the `.npmrc` file, we'll want to bubble up from the project directory, looking for `.npmrc`s first in the project, then in the user dir, then in the global config, then in the builtin npm config.

## Possible Solution

MVP: check in the project dir first (`./`), then check `~/`

long run we'll want to support:
- per-project config file (/path/to/my/project/.npmrc)
- per-user config file (~/.npmrc)
- global config file ($PREFIX/etc/npmrc)
- npm builtin config file (/path/to/npm/npmrc)

(from: https://docs.npmjs.com/files/npmrc#files)

## Context & Code Sample
working on https://github.com/ashleygwilliams/wasm-pack/pull/11 ;)

## Environment
we should keep env differences in mind, as this becomes more elaborate it'll become more of an issue.

**Comment by sendilkumarn** [comment]
how about nvmrc? can we also read that?

**Comment by yoshuawuyts** [comment]
@sendilkumarn I thought `.nvmrc` was only to set a node version? e.g. [like this](https://github.com/angular/angular/blob/master/.nvmrc). Or did you have something else in mind?

**Comment by sendilkumarn** [comment]
Yeah, it will have only the version. Well I meant nvm there. In case of nvm, I remember seeing a  `.npmrc` file will be inside `.nvm` Just to take that into account

**Comment by Michael-F-Bryan** [comment]
Would it also make sense to have a public `from_reader()` constructor which lets you load a `Npmrc` from any arbitrary source?

**Comment by yoshuawuyts** [comment]
@Michael-F-Bryan not opposed to that idea; might come in rather useful!
